server:
  port: 8081
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/files_db'
    username: root
    password: my-secret-pw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
