version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  integration-tests:
    docker:
      - image: maven:3-jdk-8-alpine
    steps:
      - checkout
      - run: mvn clean test-compile failsafe:integration-test

workflows:
  build_&_test:
    jobs:
      - maven/test
      - integration-tests